# Generated by Django 5.1.2 on 2024-10-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bone_predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_temporary/')),
            ],
        ),
    ]
